const ubicaciones = ["Autana, Amazonas",
"Atures, Amazonas",
"Manapiare, Amazonas",
"Maroa, Amazonas",
"Río Negro, Amazonas",
"Barcelona, Anzoátegui",
"Puerto La Cruz, Anzoátegui",
"Lecherías, Anzoátegui",
"El Tigre, Anzoátegui",
"Anaco, Anzoátegui",
"San Fernando, Apure",
"Achaguas, Apure",
"Biruaca, Apure",
"Elorza, Apure",
"Guasdualito, Apure",
"Maracay, Aragua",
"La Victoria, Aragua",
"Turmero, Aragua",
"Cagua, Aragua",
"San Sebastián, Aragua",
"Barinas, Barinas",
"Socopó, Barinas",
"Pedraza, Barinas",
"Rojas, Barinas",
"Obispos, Barinas",
"Ciudad Guayana, Bolívar",
"Ciudad Bolívar, Bolívar",
"El Callao, Bolívar",
"Upata, Bolívar",
"Tumeremo, Bolívar",
"Valencia, Carabobo",
"Naguanagua, Carabobo",
"Puerto Cabello, Carabobo",
"Los Guayos, Carabobo",
"Bejuma, Carabobo",
"San Carlos, Cojedes",
"Tinaquillo, Cojedes",
"El Pao, Cojedes",
"La Azulita, Cojedes",
"Macapo, Cojedes",
"Tucupita, Delta Amacuro",
"Pedernales, Delta Amacuro",
"Casacoima, Delta Amacuro",
"Antonio Díaz, Delta Amacuro",
"Juan Manuel Cajigal, Delta Amacuro",
"Coro, Falcón",
"Punto Fijo, Falcón",
"Dabajuro, Falcón",
"Carirubana, Falcón",
"Colina, Falcón",
"San Juan de los Morros, Guárico",
"Valle de la Pascua, Guárico",
"Calabozo, Guárico",
"Zaraza, Guárico",
"Ortiz, Guárico",
"Barquisimeto, Lara",
"Cabudare, Lara",
"El Tocuyo, Lara",
"Duaca, Lara",
"Quibor, Lara",
"Mérida, Mérida",
"Ejido, Mérida",
"Tovar, Mérida",
"El Vigía, Mérida",
"Santo Domingo, Mérida",
"Los Teques, Miranda",
"Petare, Miranda",
"Guatire, Miranda",
"Carrizal, Miranda",
"San Antonio de Los Altos, Miranda",
"Maturín, Monagas",
"Ezequiel Zamora (La Toscana), Monagas",
"Punta de Mata, Monagas",
"Aguasay, Monagas",
"Santa Bárbara, Monagas",
"Porlamar, Nueva Esparta",
"La Asunción, Nueva Esparta",
"Pampatar, Nueva Esparta",
"Juan Griego, Nueva Esparta",
"El Espinal, Nueva Esparta",
"Acarigua, Portuguesa",
"Guanare, Portuguesa",
"Ospino, Portuguesa",
"Biscucuy, Portuguesa",
"Araure, Portuguesa",
"Cumaná, Sucre",
"Carúpano, Sucre",
"Río Caribe, Sucre",
"Guiria, Sucre",
"Araya, Sucre",
"San Cristóbal, Táchira",
"La Fría, Táchira",
"Rubio, Táchira",
"Táriba, Táchira",
"Colón, Táchira",
"Trujillo, Trujillo",
"Valera, Trujillo",
"Boconó, Trujillo",
"San Lázaro, Trujillo",
"Carvajal, Trujillo",
"La Guaira, Vargas (La Guaira)",
"Maiquetía, Vargas (La Guaira)",
"Carabobo, Vargas (La Guaira)",
"Macuto, Vargas (La Guaira)",
"Naiguatá, Vargas (La Guaira)",
"San Felipe, Yaracuy",
"Yaritagua, Yaracuy",
"Chivacoa, Yaracuy",
"Nirgua, Yaracuy",
"Bruzual, Yaracuy",
"Maracaibo, Zulia",
"San Francisco, Zulia",
"Cidad Ojeda, Zulia",
"La Villa del Rosario, Zulia",
"Cabimas, Zulia",]

export default ubicaciones